const DATA_REQUEST = 'DATA_REQUEST';
const DATA_SUCCESS = 'DATA_SUCCESS';
const DATA_FAILURE = 'DATA_FAILURE';
const CLEAN_STATE = 'CLEAN_STATE';

export {
    DATA_REQUEST,
    DATA_SUCCESS,
    DATA_FAILURE,
    CLEAN_STATE
}